[project]
name = "hsdu"
version = "0.1.0"
description = ""
authors = [
    {name = "changhyun yi",email = "chhyyi@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "pymatgen>=2025.10.7",
    "pandas>=2.3",
    "numpy (<2.2) ; python_version >= '3.10' and python_version < '3.10'",
    "numpy (<2.5); python_version >= '3.11'",
    "scikit-learn (>=1.7.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
